### PR TITLE
Update to latest fastify 1.x and all dependencies

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
Hi, I just update all to latest Fastify 1.x, and so i had to change a little some details of the implementation (and related tests).
All other dependencies have been updated to latest release.

For the plugin release number I think something like 0.3.0 (or higher) would be good, anyway this is up to you :-) ... tell me if there is something still to fix/improve.

Thanks for this useful plugin,
Sandro

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Sorry last thing, tell me for adding a simple test of publishing a message and retrieving it (queue name could be the name and version of the plugin), if it would be good (or maybe for another PR) ... tell me as you prefer. Reference [here](https://github.com/nats-io/node-nats) .
Bye

**Comment by smartiniOnGitHub** [comment]
Sorry, do you have some news ?
Otherwise if you don't have time to manage/update it, could you transfer to me this repo, or at least transfer to me the package name at npm ? See [disputes - npm](https://docs.npmjs.com/misc/disputes.html) for more info.
Thank you very much, Sandro

**Comment by mahmed8003** [comment]
@smartiniOnGitHub Thanks for reaching out and pull request, sorry for late response, I didn't get any notification until I received your email.
I reviewed and found we need to update  "fastify-plugin": "^1.2.1", to latest. Please can you do that, and then I will merge it.

**Comment by smartiniOnGitHub** [comment]
Sure, I'll do ASAP.

Sorry for the noise, I'll keep you updated.
At this point, no problem with the package name ownership transfer to me (as in my email), thanks the same.

**Comment by mahmed8003** [comment]
@smartiniOnGitHub I took time, updated the dependencies, and published it. Thanks for your effort. I can close this now?

**Comment by smartiniOnGitHub** [comment]
sure, thank you very much and sorry again for the noise.

**Comment by mahmed8003** [comment]
No problem, Thanks.

**Pull request closed without merging**
